version: '3.8'

services:
  ner-dataset-creator:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: ner-dataset-creator-prod
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - FLASK_APP=app.py
      - PORT=5000
    volumes:
      # Mount a volume for persistent data storage
      - ner_data:/app/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    # Resource limits for production
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M

volumes:
  ner_data:
    driver: local
